[package]
name = "devises_spelljammer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.12"
tokio = { version = "1", features = ["full"] }
rand = "0.9.2"
plotters = "0.3"
serde = "1.0.197"
serde_json = "1.0.128"
chrono = "0.4.35"
resvg = "0.40.0"
dotenv = "0.15.0"
rusqlite = {version="0.37.0", features=["bundled"]}
rand_distr = "0.5.1"

[profile.release]
lto="fat"
